services:
  postgres_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - postgres_db
    restart: always
    env_file:
      - .env
  nginx:
    build:
        context: .
        dockerfile: ./docker/nginx.Dockerfile
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - type: volume
        source: static
        target: /static


networks:
  webnet:

volumes:
  static:
  pg_data: